### ISSUE TITLE
Evaluate changing repository name

### ISSUE THREAD

**Issue by CRThaze** [OpenSLO/openslo-backstage-plugins#10]
The format for the repo name seems to match more what you'd expect for a repository that contains a single plugin. But since we are building a few closely related plugins and modules in a single repository, perhaps we should change the repository name sooner rather than later to reflect that.

And example of an existing plugin repo like this is https://github.com/RoadieHQ/roadie-backstage-plugins

Perhaps: `openslo-backstage-plugins`?

**Comment by programmer04** [comment]
I'm in favor of `openslo-backstage-plugins`, so I've made a change
